Features Support
type-challenges/playground-plugin pull request #6
Opened 2021-12-06 12:05 UTC by curly210102

When I practice with type-challenges, I notice that I need a complete tool to get through the process quickly. Then I found this plugin and made some optimizations for it.

**Effect**
![31db67de83c2de209755814f2d892326846df0e1d03cf94a42e69228b1a181a0](https://user-images.githubusercontent.com/76864176/144842748-30853fd5-af27-488c-8ced-ae5ca4661b74.gif)

**Feature Supported**
- [x] Pick question in challenge list
- [x] Switch languages
- [x] Copy and share answer to github issue
- [x] Quick start next question
- [x] Quick find solutions

⚠️ type-challenges support is required, and I've create a [PR](https://github.com/type-challenges/type-challenges/pull/4939).

2021-12-06 12:09 UTC, antfu commented
@g-plane it would be great if you can have a quick review of it, or I think we could merge it first

2021-12-07 01:55 UTC, g-plane requested changes
Though I haven't run it locally, code looks OK, but there're some trivial problems.

2021-12-07 01:55 UTC, g-plane commented on README.md
> +- [x] Copy and share answer to github issue
```suggestion
- [x] Copy and share answer to GitHub issue
```

2021-12-07 01:55 UTC, g-plane commented on README.md
> +tick the **Connect to localhost:5000** in bottom of Plugins Panel, Refresh browser page.
```suggestion
tick the **Connect to localhost:5000** in bottom of Plugins Panel, and refresh browser page.
```

2021-12-07 01:55 UTC, g-plane commented on src/components/Challenges.svelte
> +      // 切换语言
Using English comments will be better.

2021-12-07 01:55 UTC, g-plane commented on src/components/Challenges.svelte
> +      // 选择题目
Same as above. Using English comments will be better.

2021-12-07 01:55 UTC, g-plane commented on src/components/Description.svelte
>    onMount(async () => {
```suggestion
  onMount(() => {
```

2021-12-07 01:55 UTC, g-plane commented on src/components/Description.svelte
> +        return await markdownToHtml(readme, context.sandbox);
We aren't in `try`...`catch` block, so we can simplify like this:

```suggestion
        return markdownToHtml(readme, context.sandbox);
```

2021-12-07 01:55 UTC, g-plane commented on src/components/Description.svelte
> +      .catch(() => {
Consider using `async`/`await` here?

2021-12-07 04:45 UTC, curly210102 commented on src/components/Description.svelte
> +        return await markdownToHtml(readme, context.sandbox);
There need to wait for code colorize to complete

https://github.com/type-challenges/playground-plugin/blob/b8dc614740784ae956523a30a744ccf4a8a6ea10/src/markdown.ts#L30-L41

2021-12-07 06:08 UTC, g-plane commented on src/components/Description.svelte
> +        return await markdownToHtml(readme, context.sandbox);
I know, but here it just returns the result of `markdownToHtml`, so nothing different. Anyway, this isn't blocker.

2021-12-07 06:09 UTC, g-plane approved these changes
Thanks!

2021-12-07 06:27 UTC, merged